name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build image ${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - base
          - node
          - nginx
          - php
          - solr
          - kubebuilder

    steps:
      - uses: actions/checkout@v1
      - name: Login to GitHub Docker Registry
        run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: cd ${{ matrix.image }} && make build
      - name: Push the Docker image
        run: cd ${{ matrix.image }} && make push
