name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build image ${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - base
          - nginx
          - php
          - solr
          - kubebuilder
  
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: cd ${{ matrix.image }} && make build
      - name: Push the Docker image
        run: cd ${{ matrix.image }} && make push
